version: '3.9'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-comm-rgem
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipassword
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
